### ISSUE TITLE
"Advance Posting of Potential Discussion Topics" doesn't really apply for this class

### ISSUE THREAD

**Issue by depstein** [uwcse510/web-cse599-hcde548-sp16#17]
The prompts are borrowed from 510 and don't feel particularly consistent with the in-class messaging on what to post about.

**Comment by jayfo** [comment]
How so?  All of those feel like prompts which could help surface things to discuss?

**Comment by depstein** [comment]
The actually important line is buried behind them: "Importantly, we also do
not want to have the discussion on Canvas. The goal of surfacing potential
discussion topics is to then have the actual discussion in-class."

The prompts facilitate things that could be discussed, but their presence
makes me think I should be discussing them in my posts (which is what they
had to do in 510).

~Daniel Epstein

**Comment by jayfo** [comment]
I tweaked the prompt in #18. I don't see anything else actionable here.

Feel free to suggest concrete changes.
